apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.prometheus.auth.serviceAccountName }}
  namespace: {{ include "rhocp-keda-crs.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.prometheus.auth.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.prometheus.auth.serviceAccountName }} 
  namespace: {{ include "rhocp-keda-crs.namespace" . }}