apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: broker-servicemonitor
  namespace: {{ include "amq-broker-crs.namespace" . }}
spec:
  endpoints:
    - interval: 15s
      port: wconsj-.*
      # scheme: https
      # tlsConfig:
      #   insecureSkipVerify: true
  podTargetLabels:
    - ActiveMQArtemis
    - application
  selector:
    matchLabels:
      ActiveMQArtemis: amq-keda
  jobLabel: ActiveMQArtemis