apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-custom-metrics-autoscaler-operator
  labels:
    {{- include "rhocp-keda-operator.labels" . | nindent 4 }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: openshift-custom-metrics-autoscaler-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # startingCSV: custom-metrics-autoscaler.v2.7.1